# Generated by Django 4.0.4 on 2022-05-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cnt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
